name: Deploy Azure Functions Backend

on:
  push:
    branches:
      - main
    paths:
      - 'azure-functions/**'
      - '.github/workflows/azure-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './azure-functions'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'trackademic-api'
        slot-name: 'Production'
        package: './azure-functions'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
