name: CI/CD Frontend with API

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend Build & Deploy with API
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Python for API
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install API dependencies
        run: |
          cd frontend/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build And Deploy Frontend with API
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_TREE_09B213203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          api_location: "./frontend/api"
          api_language: "python"
          api_version: "3.11"
          output_location: "dist"