name: CI/CD (Frontend & Backend)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend == 'true' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Frontend Build & Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy Frontend
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_TREE_09B213203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          api_location: ""
          output_location: "dist"

  backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend == 'true' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Backend Build & Deploy
    env:
      AZURE_WEBAPP_NAME: trackademic-backend
      AZURE_RESOURCE_GROUP: trackademic-frontend_group
      AZURE_PYTHON_VERSION: '3.10'
      BACKEND_PATH: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.AZURE_PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.BACKEND_PATH }}/requirements.txt

      - name: Zip backend code
        run: |
          cd ${{ env.BACKEND_PATH }}
          zip -r ../backend.zip .
          cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}